import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card } from '@/components/ui/card';
import { ArrowLeft, Save } from 'lucide-react';
import { FormSection } from '@/components/forms/FormSection';
import { FormField } from '@/components/forms/FormField';
import { useToast } from '@/hooks/use-toast';
import { savePatientMedicalInfo } from '@/services/patientMedicalInfoService';
import { createTokenForPatient } from '@/services/tokenService';
import { supabase } from '@/utils/supabase';

const PatientMedicalForm = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(false);
  const [formData, setFormData] = useState({
    // Personal Details (matching registration desk)
    firstName: '',
    surname: '',
    mobileNumber: '',
    age: '',
    gender: '',
    purposeOfVisit: '',
    address: '',
    occupation: '',
    income: '',
    billingType: '',
    
    // Medical Information
    chronic_conditions: '',
    allergies: '',
    current_medications: '',
  });

  const GENDER_OPTIONS = [
    { value: 'Male', label: 'Male' },
    { value: 'Female', label: 'Female' },
    { value: 'Other', label: 'Other' },
  ];

  const BILLING_TYPE_OPTIONS = [
    { value: 'BPL', label: 'BPL (Below Poverty Line)' },
    { value: 'RBSK', label: 'RBSK' },
    { value: 'ESI', label: 'ESI (Employee State Insurance)' },
    { value: 'Senior Citizen', label: 'Senior Citizen' },
    { value: 'Poor', label: 'Poor' },
    { value: 'Amarnath Yatra', label: 'Amarnath Yatra' },
    { value: 'Medical Student', label: 'Medical Student' },
    { value: 'Hospital Staff', label: 'Hospital Staff' },
    { value: 'Handicapped', label: 'Handicapped' },
    { value: 'General', label: 'General' },
  ];

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({
      ...prev,
      [field]: value,
    }));
  };

  const handleMobileChange = (value: string) => {
    const numericValue = value.replace(/\D/g, '').slice(0, 10);
    handleInputChange('mobileNumber', numericValue);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Validation
    if (!formData.firstName || !formData.surname || !formData.mobileNumber || !formData.age || !formData.gender || !formData.purposeOfVisit) {
      toast({
        title: "Missing Required Fields",
        description: "Please fill in all required fields",
        variant: "destructive",
      });
      return;
    }

    // Validate phone number
    if (!/^\d{10}$/.test(formData.mobileNumber)) {
      toast({
        title: "Invalid Mobile Number",
        description: "Please enter a valid 10-digit mobile number",
        variant: "destructive",
      });
      return;
    }

    setIsLoading(true);
    
    try {
      if (!user?.id) {
        throw new Error('User not authenticated');
      }

      // Save medical information using the unified service
      const result = await savePatientMedicalInfo(
        {
          patient_id: '', // Will be generated by service
          full_name: `${formData.firstName} ${formData.surname}`,
          age: formData.age,
          gender: formData.gender,
          phone: formData.mobileNumber,
          email: '',
          address: formData.address,
          city: '',
          state: '',
          pincode: '',
          blood_group: '',
          chief_complaint: formData.purposeOfVisit,
          symptoms: '',
          chronic_conditions: formData.chronic_conditions,
          allergies: formData.allergies,
          current_medications: formData.current_medications,
          source: 'manual', // Mark as manually filled
        },
        user.id
      );

      // Get the patient ID from the saved result
      const patientId = result?.id;
      if (!patientId) {
        throw new Error('Failed to retrieve patient ID');
      }

      // Get hospital ID from sessionStorage or patient record
      const selectedHospitalId = sessionStorage.getItem('selected_hospital_id');
      
      // If no selected hospital, try to get from patient record
      let hospitalId = selectedHospitalId;
      if (!hospitalId) {
        const { data: patient } = await supabase
          .from('patients')
          .select('hospital_id')
          .eq('id', patientId)
          .single();
        
        hospitalId = patient?.hospital_id || null;
      }

      // Generate token
      let tokenNumber = null;
      if (hospitalId) {
        const token = await createTokenForPatient({
          patientId,
          chiefComplaint: formData.purposeOfVisit,
          symptoms: [],
          visitType: 'General Consultation',
          hospitalId,
        });
        tokenNumber = token.token_number;
      }

      toast({
        title: "Success",
        description: tokenNumber 
          ? `Your token ${tokenNumber} has been generated`
          : "Your medical information has been saved",
        variant: "default",
      });

      console.log('Medical info saved and token generated:', { result, tokenNumber });
      navigate('/patient');
    } catch (error) {
      console.error('Error saving form:', error);
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to save form",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="bg-card border-b border-border">
        <div className="px-6 py-4 flex items-center gap-4">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate('/patient')}
            className="text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back
          </Button>
          <h1 className="text-2xl font-bold text-foreground">Medical Form - Fill Manually</h1>
        </div>
      </header>

      {/* Main Content */}
      <main className="w-full p-6">
        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Personal Details Section */}
          <Card className="p-6">
            <FormSection 
              title="Personal Details" 
              description="Provide your basic personal information"
            >
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField label="First Name" required>
                  <Input
                    type="text"
                    placeholder="First name"
                    value={formData.firstName}
                    onChange={(e) => handleInputChange('firstName', e.target.value)}
                  />
                </FormField>

                <FormField label="Surname" required>
                  <Input
                    type="text"
                    placeholder="Surname"
                    value={formData.surname}
                    onChange={(e) => handleInputChange('surname', e.target.value)}
                  />
                </FormField>
              </div>

              <FormField label="Mobile Number (10 digits)" required>
                <Input
                  type="tel"
                  placeholder="10-digit mobile number"
                  maxLength={10}
                  value={formData.mobileNumber}
                  onChange={(e) => handleMobileChange(e.target.value)}
                />
              </FormField>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField label="Age" required>
                  <Input
                    type="number"
                    placeholder="Age"
                    value={formData.age}
                    onChange={(e) => handleInputChange('age', e.target.value)}
                    min={0}
                    max={150}
                  />
                </FormField>

                <FormField label="Gender" required>
                  <select
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    value={formData.gender}
                    onChange={(e) => handleInputChange('gender', e.target.value)}
                  >
                    <option value="">Select Gender</option>
                    {GENDER_OPTIONS.map(opt => (
                      <option key={opt.value} value={opt.value}>{opt.label}</option>
                    ))}
                  </select>
                </FormField>
              </div>

              <FormField label="Purpose of Visit / Chief Complaint" required>
                <Input
                  type="text"
                  placeholder="e.g., Fever, Cough, Skin issue, etc."
                  value={formData.purposeOfVisit}
                  onChange={(e) => handleInputChange('purposeOfVisit', e.target.value)}
                />
              </FormField>

              <FormField label="Address">
                <Input
                  type="text"
                  placeholder="Full address"
                  value={formData.address}
                  onChange={(e) => handleInputChange('address', e.target.value)}
                />
              </FormField>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField label="Occupation">
                  <Input
                    type="text"
                    placeholder="Occupation"
                    value={formData.occupation}
                    onChange={(e) => handleInputChange('occupation', e.target.value)}
                  />
                </FormField>

                <FormField label="Income">
                  <Input
                    type="text"
                    placeholder="Income (optional)"
                    value={formData.income}
                    onChange={(e) => handleInputChange('income', e.target.value)}
                  />
                </FormField>
              </div>

              <FormField label="Billing Type">
                <select
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  value={formData.billingType}
                  onChange={(e) => handleInputChange('billingType', e.target.value)}
                >
                  <option value="">Select Billing Type</option>
                  {BILLING_TYPE_OPTIONS.map(opt => (
                    <option key={opt.value} value={opt.value}>{opt.label}</option>
                  ))}
                </select>
              </FormField>
            </FormSection>
          </Card>

          {/* Medical Information Section */}
          <Card className="p-6">
            <FormSection 
              title="Medical Information" 
              description="Provide details about your medical history"
            >
              <FormField label="Chronic Conditions">
                <textarea
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 min-h-[80px]"
                  placeholder="List any chronic conditions (diabetes, hypertension, asthma, etc. - separate by commas)"
                  value={formData.chronic_conditions}
                  onChange={(e) => handleInputChange('chronic_conditions', e.target.value)}
                />
              </FormField>

              <FormField label="Allergies">
                <textarea
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 min-h-[80px]"
                  placeholder="List any known allergies (medications, foods, environmental, etc. - separate by commas)"
                  value={formData.allergies}
                  onChange={(e) => handleInputChange('allergies', e.target.value)}
                />
              </FormField>

              <FormField label="Current Medications">
                <textarea
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 min-h-[80px]"
                  placeholder="List all current medications with dosages (separate by commas)"
                  value={formData.current_medications}
                  onChange={(e) => handleInputChange('current_medications', e.target.value)}
                />
              </FormField>
            </FormSection>
          </Card>

          {/* Action Buttons */}
          <div className="flex gap-3 justify-start">
            <Button
              type="submit"
              className="bg-emerald-700 hover:bg-emerald-800 text-white"
              disabled={isLoading}
            >
              <Save className="h-4 w-4 mr-2" />
              {isLoading ? 'Saving...' : 'Save Form'}
            </Button>
            <Button
              type="button"
              variant="outline"
              onClick={() => navigate('/patient')}
              disabled={isLoading}
            >
              Cancel
            </Button>
          </div>
        </form>
      </main>
    </div>
  );
};

export default PatientMedicalForm;
